#pragma once

// One grass-clump anchor: derived 1:1 from an EXISTING vegetation instance
// (the payload generated by VegetationRenderer for each vegetation placement:
// world position, billboard type/biome index and smooth surface normal). The
// vegetation instance remains the single source of truth — this anchor is the
// conversion boundary into the generic SDF scene, exactly like FlameAnchor and
// RockAnchor, and never places grass on its own. CPU-only input to
// createGrassFromAnchors (becomes one Grass Instance per anchor, which the
// shader expands into many procedural blades).
#include <cstdint>

#include <glm/glm.hpp>

namespace sdf_gpu {

struct GrassAnchor {
    glm::vec3 pos = glm::vec3(0.0f);                 // clump base (vegetation world position)
    float seed = 0.0f;                               // deterministic per-clump variation
    glm::vec3 normal = glm::vec3(0.0f, 1.0f, 0.0f);  // smooth terrain normal (vegetation payload)
    float scale = 1.0f;                              // world size (billboardScale x height variation)
    uint32_t type = 0u;                              // existing vegetation type/biome (0..2)
};

} // namespace sdf_gpu
